name: Test

on:
  push:
    branches:
      - master
      - dev
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.5']
        os: [ubuntu-18.04]
        architecture: [x64]
        python-version: ['2.7']
        julia-version: ['1.5', 'nightly']
    steps:
      - uses: julia-actions/setup-julia@v1.5
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.architecture }}
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: melodic
      - run: "source /opt/ros/melodic/setup.sh && roscore &"
      - run: "sleep 5 && julia --project=docs/ -e 'using Pkg; Pkg.test("ROSTransforms");'"
      - run: "source /opt/ros/melodic/setup.sh && roscore"
          julia --project=docs/ -e 'using Pkg; Pkg.test("ROSTransforms");'
          killall roscore
      - name: Launch ROS & Test Package
        run: |
          roscore &
          sleep 5
          julia --project=docs/ -e 'using Pkg; Pkg.test("ROSTransforms");'
          killall roscore
